version: '3'

services:
  database:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=keycloak
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - kcnetwork

  keycloak_1:
    build:
      context: .
      dockerfile: keycloak/Dockerfile
    environment:
#      KC_PROXY_HEADERS: xforwarded
#      KC_HTTP_ENABLED: true
#      KC_PROXY: edge
      KC_HOSTNAME_STRICT: false
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: INFO
      KC_HTTP_PORT: 8080
      KC_HTTPS_PORT: 8443
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - kcnetwork
    depends_on:
      - database

  keycloak_2:
    build:
      context: .
      dockerfile: keycloak/Dockerfile
    environment:
#      KC_PROXY_HEADERS: xforwarded
#      KC_HTTP_ENABLED: true
#      KC_PROXY: edge
      KC_HOSTNAME_STRICT: false
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: INFO
      KC_HTTP_PORT: 8180
      KC_HTTPS_PORT: 8543
    ports:
      - "8180:8180"
      - "8543:8543"
    networks:
      - kcnetwork
    depends_on:
      - database

  keycloak_3:
    build:
      context: .
      dockerfile: keycloak/Dockerfile
    environment:
#      KC_PROXY_HEADERS: xforwarded
#      KC_HTTP_ENABLED: true
#      KC_PROXY: edge
      KC_HOSTNAME_STRICT: false
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: INFO
      KC_HTTP_PORT: 8380
      KC_HTTPS_PORT: 8643
    ports:
      - "8380:8380"
      - "8643:8643"
    networks:
      - kcnetwork
    depends_on:
      - database

volumes:
  pgdata:

networks:
  kcnetwork:

